<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Lychee.Publisher.Application</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\9.0.17\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Lychee.Publisher.Domain">
      <HintPath>..\Lychee.Publisher.Api\bin\Debug\net9.0\Lychee.Publisher.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>